name: Check Updates
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-bump-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install
    - run: npm list
    - run: node ./utils/check_updates.mjs static/versions-v1.json
    - if: ${{ github.event != 'pull_request' }}
      uses: peter-evans/create-pull-request@v6
      with:
        branch: auto-bump-versions
        commit-message: "update CUDA versions list"
        add-paths: ./static/versions-v1.json
        title: "Update CUDA Versions list"
        body: ""
