name: Check Updates
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-bump-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm list
    - run: node ./utils/check_updates.mjs static/versions-v1.json
    - uses: peter-evans/create-pull-request@v5
      with:
        branch: auto-bump-versions
        commit-message: "update CUDA versions list"
        add-paths: ./static/versions-v1.json
        title: "Update CUDA Versions list"
        body: ""
